name: Build and Release

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the version of .NET Core SDK

    - name: Restore dependencies
      run: dotnet restore WebAuthenticator/WebAuthenticator.Server/WebAuthenticator.Server.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore WebAuthenticator/WebAuthenticator.Server/WebAuthenticator.Server.sln

    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: web-app
        path: |
          WebAuthenticator/WebAuthenticator.Server/Path/To/Published/Files  # Adjust this path to your publish output

  # Optionally, you can add a step to notify Slack or other tools about the build result
  notify:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        status: ${{ job.status }}
        mention: here
        message: 'Build ${GITHUB_RUN_ID} completed for ${GITHUB_REPOSITORY}:${GITHUB_REF}'
